dependencies:
- name: jenkins
  version: 1.4.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: jenkins.enabled
- name: kafka
  version: 0.16.2
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: kafka.enabled
